"use client";

import { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle, CheckCircle2, ChevronDown, ChevronUp, Clock, Droplets,
  Eye, Filter, Gauge, RefreshCw, ShieldAlert, Thermometer, Wifi, WifiOff,
} from "lucide-react";

type Detection = { is_anomaly: boolean; type: string; severity: string; confidence: number; reason: string; class_probabilities?: Record<string, number> };
type TelemetryPoint = { timestamp: string; temperature: number | null; pressure: number | null; humidity: number | null };
type OperatorDecision = { decision: string; station_id: string; timestamp: string } | null;
type Anomaly = { station_id: string; timestamp: string; temperature: number | null; pressure: number | null; humidity: number | null; history_size: number; detection: Detection; telemetry_context?: TelemetryPoint[]; operator_decision?: OperatorDecision };
type FilterType = "ALL" | "SPIKE" | "DRIFT" | "FROZEN_SENSOR" | "STEP_CHANGE" | "MISSING_DATA";

const STATION_ID = "LUCKNOW_001";
const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
const WS_BASE = process.env.NEXT_PUBLIC_WS_URL ?? API_BASE.replace(/^http/, "ws");
const decisionLabels: Record<string, string> = { SENSOR_FAULT: "Sensor Fault", VALID_WEATHER_EVENT: "Valid Weather Event", FALSE_ALARM: "False Alarm" };
const anomalyTitle = (type: string) => type.replaceAll("_", " ");
const formatTime = (timestamp: string) => new Date(timestamp).toLocaleString([], { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", second: "2-digit" });
const formatValue = (value: number | null, unit: string) => value == null || Number.isNaN(value) ? "—" : `${value.toFixed(1)} ${unit}`;
const severityClasses = (severity: string) => severity === "HIGH" ? "border-rose-500/30 bg-rose-500/10 text-rose-300" : severity === "MEDIUM" ? "border-amber-500/30 bg-amber-500/10 text-amber-300" : "border-slate-700 bg-slate-900 text-slate-400";

function ExpectedObserved({ item }: { item: Anomaly }) {
  const points = item.telemetry_context ?? [];
  const vars = [
    ["Temperature", "°C", item.temperature, (p: TelemetryPoint) => p.temperature],
    ["Relative humidity", "%", item.humidity, (p: TelemetryPoint) => p.humidity],
    ["Atmospheric pressure", "hPa", item.pressure, (p: TelemetryPoint) => p.pressure],
  ] as const;
  return <div className="rounded-xl border border-amber-500/20 bg-amber-500/[0.035] p-4">
    <div className="flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-[10px] font-mono uppercase tracking-widest text-amber-400">Expected vs observed</div><div className="mt-1 text-xs text-slate-400">Expected = mean of the preceding evidence readings. Observed = flagged reading.</div></div><div className="text-[10px] font-mono text-slate-600">BASELINE → FLAGGED</div></div>
    <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-3">{vars.map(([key, unit, observed, get]) => { const previous = points.slice(0, -1).map(get).filter((v): v is number => v != null && Number.isFinite(v)); const expected = previous.length ? previous.reduce((a, b) => a + b, 0) / previous.length : null; const delta = expected != null && observed != null ? observed - expected : null; const relative = expected != null && observed != null && expected !== 0 ? Math.abs(delta! / expected) * 100 : null; return <div key={key} className="rounded-lg border border-slate-800 bg-slate-950/70 p-4"><div className="text-[10px] font-mono uppercase tracking-widest text-slate-500">{key}</div><div className="mt-3 grid grid-cols-2 gap-3"><div><div className="text-[9px] uppercase tracking-widest text-slate-600">Expected</div><div className="mt-1 font-mono text-sm text-slate-300">{formatValue(expected, unit)}</div></div><div><div className="text-[9px] uppercase tracking-widest text-amber-500/80">Observed</div><div className="mt-1 font-mono text-sm font-bold text-amber-300">{formatValue(observed, unit)}</div></div></div><div className="mt-3 border-t border-slate-800 pt-2 flex justify-between"><span className="text-[9px] uppercase tracking-widest text-slate-600">Deviation</span><span className="font-mono text-xs font-bold text-amber-300">{delta == null ? "—" : `${delta >= 0 ? "+" : ""}${delta.toFixed(1)} ${unit}`} {relative != null && <span className="text-slate-600">({relative.toFixed(1)}%)</span>}</span></div></div> })}</div>
  </div>;
}

function EvidenceSeries({ label, unit, points, getValue, strokeClass }: { label: string; unit: string; points: TelemetryPoint[]; getValue: (p: TelemetryPoint) => number | null; strokeClass: string }) {
  const values = points.map(getValue); const numeric = values.filter((v): v is number => v != null && Number.isFinite(v));
  if (!numeric.length) return <div className="rounded-lg border border-slate-800 p-4 text-xs text-slate-600">{label}: no data</div>;
  const W=900,H=150,L=52,R=18,T=16,B=25,plotW=W-L-R,plotH=H-T-B,min0=Math.min(...numeric),max0=Math.max(...numeric),pad=max0===min0?Math.max(Math.abs(min0)*.02,.5):(max0-min0)*.12,min=min0-pad,max=max0+pad,range=max-min||1;
  const x=(i:number)=>L+(i/Math.max(1,points.length-1))*plotW,y=(v:number)=>T+(1-(v-min)/range)*plotH; let path=""; values.forEach((v,i)=>{if(v==null||!Number.isFinite(v)){path="";return;} path+=`${path?" L":"M"}${x(i).toFixed(1)} ${y(v).toFixed(1)}`;});
  const latest=values.length-1, latestValue=values[latest];
  return <div className="rounded-lg border border-slate-800 bg-slate-950/50 p-3"><div className="flex justify-between"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${strokeClass.replace("text-", "bg-")}`} /><span className="text-[10px] font-mono uppercase tracking-widest text-slate-400">{label}</span></div><span className="text-[10px] font-mono text-slate-600">{min0.toFixed(1)}–{max0.toFixed(1)} {unit}</span></div><div className="mt-2 overflow-x-auto"><svg viewBox={`0 0 ${W} ${H}`} className="h-[150px] min-w-[720px] w-full"><line x1={L} x2={W-R} y1={T+plotH} y2={T+plotH} stroke="currentColor" className="text-slate-700" />{[0,.5,1].map(r=><g key={r}><line x1={L} x2={W-R} y1={T+r*plotH} y2={T+r*plotH} stroke="currentColor" className="text-slate-800"/><text x={L-7} y={T+r*plotH+3} textAnchor="end" className="fill-slate-600 text-[9px]">{(max-r*range).toFixed(1)}</text></g>)}<path d={path} fill="none" stroke="currentColor" className={strokeClass} strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round"/>{latestValue!=null&&<><line x1={x(latest)} x2={x(latest)} y1={T} y2={T+plotH} stroke="currentColor" strokeDasharray="4 4" className="text-amber-400/70"/><circle cx={x(latest)} cy={y(latestValue)} r="5" className="fill-amber-400"/><text x={Math.min(W-8,x(latest)+8)} y={Math.max(13,y(latestValue)-8)} className="fill-amber-400 text-[9px]">FLAGGED</text></>}<text x={L} y={H-7} className="fill-slate-600 text-[9px]">{new Date(points[0].timestamp).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</text><text x={W-R} y={H-7} textAnchor="end" className="fill-slate-600 text-[9px]">{new Date(points[points.length-1].timestamp).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</text></svg></div></div>;
}

function EvidenceChart({ points, type }: { points: TelemetryPoint[]; type: string }) { return <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex justify-between"><div><div className="text-[10px] font-mono uppercase tracking-widest text-slate-500">Telemetry evidence</div><div className="mt-1 text-xs text-slate-400">Independent scales, shared time axis. The final reading is the flagged observation.</div></div><div className="text-[10px] font-mono text-amber-400">{anomalyTitle(type)}</div></div><div className="mt-4 space-y-3"><EvidenceSeries label="Temperature" unit="°C" points={points} getValue={p=>p.temperature} strokeClass="text-rose-400"/><EvidenceSeries label="Relative Humidity" unit="%" points={points} getValue={p=>p.humidity} strokeClass="text-sky-400"/><EvidenceSeries label="Atmospheric Pressure" unit="hPa" points={points} getValue={p=>p.pressure} strokeClass="text-violet-400"/></div></div>; }

export default function AnomalyReviewPage() {
  const [anomalies,setAnomalies]=useState<Anomaly[]>([]); const [filter,setFilter]=useState<FilterType>("ALL"); const [expanded,setExpanded]=useState<string|null>(null); const [connection,setConnection]=useState("connecting"); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const keyOf=(item:Anomaly)=>`${item.station_id}-${item.timestamp}`;
  const loadAnomalies=async()=>{try{const r=await fetch(`${API_BASE}/anomalies?station_id=${encodeURIComponent(STATION_ID)}`,{cache:"no-store"});if(!r.ok)throw new Error();const d=await r.json();setAnomalies(d.anomalies??[]);setError(null);}catch{setError("Unable to load anomaly history from the AeroAlert backend.");}finally{setLoading(false);}};
  useEffect(()=>{let cancelled=false;let timer:ReturnType<typeof setTimeout>|undefined;let socket:WebSocket|null=null;loadAnomalies();const connect=()=>{if(cancelled)return;socket=new WebSocket(`${WS_BASE}/ws?station_id=${encodeURIComponent(STATION_ID)}`);socket.onopen=()=>!cancelled&&setConnection("live");socket.onmessage=e=>{try{const msg=JSON.parse(e.data);if(msg.type==="operator_decision"){setAnomalies(cur=>cur.map(a=>keyOf(a)===`${msg.station_id}-${msg.timestamp}`?{...a,operator_decision:msg}:a));return;}if(!msg.detection?.is_anomaly)return;setAnomalies(cur=>[msg,...cur.filter(a=>a.timestamp!==msg.timestamp)].slice(0,100));}catch{setError("Received invalid live anomaly data.");}};socket.onerror=()=>!cancelled&&setError("Live anomaly stream connection failed.");socket.onclose=()=>{if(!cancelled){setConnection("reconnecting");timer=setTimeout(connect,1500);}};};connect();return()=>{cancelled=true;if(timer)clearTimeout(timer);socket?.close();};},[]);
  const submitDecision=async(item:Anomaly,decision:string)=>{try{const url=`${API_BASE}/anomalies/${encodeURIComponent(item.station_id)}/${encodeURIComponent(item.timestamp)}/decision`;const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision})});if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.detail??"Decision failed");}const saved=await r.json();setAnomalies(cur=>cur.map(a=>keyOf(a)===keyOf(item)?{...a,operator_decision:saved}:a));setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to save operator decision.");}};
  const filtered=useMemo(()=>filter==="ALL"?anomalies:anomalies.filter(a=>a.detection.type===filter),[anomalies,filter]); const high=anomalies.filter(a=>a.detection.severity==="HIGH").length; const reviewed=anomalies.filter(a=>!!a.operator_decision).length;

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 border-b border-slate-800 pb-5 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-2 text-[11px] font-mono uppercase tracking-[0.18em] text-amber-400"><ShieldAlert className="h-3.5 w-3.5"/> Quality control queue</div><h1 className="mt-2 text-xl font-bold text-slate-100 font-mono uppercase">Anomaly Review</h1><p className="mt-1 max-w-3xl text-xs leading-relaxed text-slate-400">Review an AI flag, inspect its telemetry evidence, then classify it as a sensor fault, valid weather event, or false alarm.</p></div><div className="flex gap-2"><span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-mono ${connection==="live"?"border-emerald-500/30 bg-emerald-500/10 text-emerald-400":"border-slate-700 bg-slate-900 text-slate-400"}`}>{connection==="live"?<Wifi className="h-3.5 w-3.5"/>:<WifiOff className="h-3.5 w-3.5"/>}{connection==="live"?"LIVE":connection.toUpperCase()}</span><button onClick={loadAnomalies} className="inline-flex items-center gap-2 rounded border border-slate-700 bg-slate-900 px-3 py-1.5 text-xs font-mono text-slate-300"><RefreshCw className="h-3.5 w-3.5"/> Refresh</button></div></div>
    {error&&<div className="rounded-lg border border-amber-500/20 bg-amber-500/5 px-4 py-3 text-xs text-amber-200">{error}</div>}
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><div className="text-[10px] uppercase tracking-widest text-slate-500">Flagged readings</div><div className="mt-2 font-mono text-2xl font-bold text-slate-100">{anomalies.length}</div><div className="mt-1 text-[11px] text-slate-500">Current in-memory queue</div></div><div className="rounded-xl border border-rose-500/20 bg-rose-500/5 p-4"><div className="text-[10px] uppercase tracking-widest text-rose-400">High severity</div><div className="mt-2 font-mono text-2xl font-bold text-rose-300">{high}</div><div className="mt-1 text-[11px] text-slate-500">Immediate attention</div></div><div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4"><div className="text-[10px] uppercase tracking-widest text-emerald-400">Operator reviewed</div><div className="mt-2 font-mono text-2xl font-bold text-emerald-300">{reviewed}</div><div className="mt-1 text-[11px] text-slate-500">Decisions recorded</div></div><div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><div className="text-[10px] uppercase tracking-widest text-slate-500">Station</div><div className="mt-2 font-mono text-lg font-bold text-slate-100">{STATION_ID}</div><div className="mt-1 text-[11px] text-slate-500">48-reading inference window</div></div></div>
    <div className="flex flex-col gap-3 rounded-xl border border-slate-800 bg-slate-900/40 p-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-2 text-xs font-mono text-slate-400"><Filter className="h-4 w-4"/> Filter fault class</div><div className="flex flex-wrap gap-2">{(["ALL","SPIKE","DRIFT","FROZEN_SENSOR","STEP_CHANGE","MISSING_DATA"] as FilterType[]).map(t=><button key={t} onClick={()=>setFilter(t)} className={`rounded-full border px-3 py-1.5 text-[10px] font-mono uppercase ${filter===t?"border-emerald-500/40 bg-emerald-500/10 text-emerald-400":"border-slate-700 bg-slate-950 text-slate-500"}`}>{t==="ALL"?"All":anomalyTitle(t)}</button>)}</div></div>
    <div className="space-y-4">{loading?<div className="rounded-xl border border-slate-800 p-12 text-center text-sm text-slate-500">Loading anomaly history…</div>:filtered.length===0?<div className="rounded-xl border border-emerald-500/15 bg-emerald-500/5 p-12 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-400"/><h2 className="mt-3 text-sm font-bold font-mono uppercase text-slate-200">No matching anomalies</h2><p className="mt-1 text-xs text-slate-500">Run the simulator to generate a controlled fault event.</p></div>:filtered.map(item=>{const key=keyOf(item),open=expanded===key,decision=item.operator_decision?.decision;return <div key={key} className={`rounded-xl border bg-slate-900/60 ${decision?"border-emerald-500/15":"border-slate-800"}`}><div className="p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-start gap-3"><div className={`rounded-lg border p-2 ${severityClasses(item.detection.severity)}`}><AlertTriangle className="h-4 w-4"/></div><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-bold text-slate-100">{anomalyTitle(item.detection.type)}</span><span className={`rounded-full border px-2 py-0.5 text-[10px] font-mono ${severityClasses(item.detection.severity)}`}>{item.detection.severity}</span>{decision&&<span className="rounded-full border border-emerald-500/25 bg-emerald-500/5 px-2 py-0.5 text-[10px] font-mono text-emerald-400">{decisionLabels[decision]??decision}</span>}</div><div className="mt-1 flex gap-3 text-[11px] font-mono text-slate-500"><span>{item.station_id}</span><span>•</span><span>{formatTime(item.timestamp)}</span></div></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 xl:min-w-[520px]"><div><div className="text-[9px] uppercase tracking-widest text-slate-600">Temperature</div><div className="mt-1 font-mono text-xs text-slate-200">{formatValue(item.temperature,"°C")}</div></div><div><div className="text-[9px] uppercase tracking-widest text-slate-600">Humidity</div><div className="mt-1 font-mono text-xs text-slate-200">{formatValue(item.humidity,"%")}</div></div><div><div className="text-[9px] uppercase tracking-widest text-slate-600">Pressure</div><div className="mt-1 font-mono text-xs text-slate-200">{formatValue(item.pressure,"hPa")}</div></div><div><div className="text-[9px] uppercase tracking-widest text-slate-600">Confidence</div><div className="mt-1 font-mono text-xs font-bold text-emerald-400">{(item.detection.confidence*100).toFixed(1)}%</div></div></div></div>
      <div className="mt-4 rounded-lg border border-slate-800 bg-slate-950/60 p-4"><div className="flex items-center gap-2 text-[10px] font-mono uppercase tracking-widest text-slate-500"><Eye className="h-3.5 w-3.5"/> Model explanation</div><p className="mt-2 text-xs leading-relaxed text-slate-300">{item.detection.reason}</p></div>
      <div className="mt-4 rounded-lg border border-slate-800 bg-slate-950/40 p-3"><div className="text-[10px] font-mono uppercase tracking-widest text-slate-600">Operator decision</div><div className="mt-2 flex flex-wrap gap-2">{(["SENSOR_FAULT","VALID_WEATHER_EVENT","FALSE_ALARM"] as const).map(d=><button key={d} onClick={()=>submitDecision(item,d)} className={`rounded border px-3 py-2 text-[10px] font-mono uppercase transition ${decision===d?"border-emerald-500/40 bg-emerald-500/10 text-emerald-300":"border-slate-700 bg-slate-950 text-slate-400 hover:border-slate-500 hover:text-slate-200"}`}>{decision===d?<CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>:null}{decisionLabels[d]}</button>)}</div><p className="mt-2 text-[10px] text-slate-600">This decision is stored by the prototype backend and is shared with connected review clients.</p></div>
      <div className="mt-4 flex items-center justify-between border-t border-slate-800/70 pt-4"><button onClick={()=>setExpanded(open?null:key)} className="inline-flex items-center gap-2 text-xs font-mono text-slate-400 hover:text-slate-200">{open?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}{open?"Hide telemetry evidence":"Inspect telemetry evidence"}</button>{decision&&<span className="text-[10px] font-mono text-emerald-500/70">DECISION RECORDED</span>}</div>
      {open&&<div className="mt-4 space-y-4 border-t border-slate-800 pt-4"><ExpectedObserved item={item}/><EvidenceChart points={item.telemetry_context??[]} type={item.detection.type}/><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><div className="rounded-lg border border-slate-800 p-4"><div className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-slate-500"><Thermometer className="h-3.5 w-3.5"/>Temperature</div><div className="mt-2 font-mono text-lg text-slate-100">{formatValue(item.temperature,"°C")}</div></div><div className="rounded-lg border border-slate-800 p-4"><div className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-slate-500"><Droplets className="h-3.5 w-3.5"/>Humidity</div><div className="mt-2 font-mono text-lg text-slate-100">{formatValue(item.humidity,"%")}</div></div><div className="rounded-lg border border-slate-800 p-4"><div className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-slate-500"><Gauge className="h-3.5 w-3.5"/>Pressure</div><div className="mt-2 font-mono text-lg text-slate-100">{formatValue(item.pressure,"hPa")}</div></div></div><div className="rounded-lg border border-slate-800 p-4"><div className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-slate-500"><Clock className="h-3.5 w-3.5"/>Inference context</div><div className="mt-3 grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs font-mono"><div><span className="text-slate-600">History</span><div className="mt-1 text-slate-300">{item.history_size}</div></div><div><span className="text-slate-600">Evidence</span><div className="mt-1 text-slate-300">{item.telemetry_context?.length??0}</div></div><div><span className="text-slate-600">Decision</span><div className="mt-1 text-emerald-300">{decision?decisionLabels[decision]:"Pending"}</div></div><div><span className="text-slate-600">Time</span><div className="mt-1 text-slate-300">{formatTime(item.timestamp)}</div></div></div></div>{item.detection.class_probabilities&&<div className="rounded-lg border border-slate-800 p-4"><div className="text-[10px] uppercase tracking-widest text-slate-500">Class probabilities</div><div className="mt-3 grid grid-cols-2 sm:grid-cols-5 gap-2">{Object.entries(item.detection.class_probabilities).map(([name,p])=><div key={name} className="rounded border border-slate-800 p-2"><div className="truncate text-[9px] text-slate-600">{name}</div><div className="mt-1 font-mono text-xs text-slate-300">{(p*100).toFixed(1)}%</div></div>)}</div></div>}</div>}
    </div></div>})}</div>
    <div className="rounded-lg border border-slate-800 bg-slate-900/30 p-4 text-[11px] leading-relaxed text-slate-600">Operator decisions are intentionally stored in-memory for the prototype. Restarting FastAPI clears them. In a production deployment, decisions would be persisted with operator identity, timestamp, and audit history.</div>
  </div>;
}
